### ISSUE TITLE
Fail to pip install scikit-robot

### ISSUE THREAD

**Issue by shmpwk** [iory/scikit-robot#161]
When I tried to install scikit-robot like
```
$ pip install scikit-robot
```
The outputs were like this.
```
Collecting scikit-robot
  Using cached scikit-robot-0.0.9.tar.gz (703 kB)
Collecting cached-property
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting cvxopt
  Using cached cvxopt-1.2.5-cp36-cp36m-manylinux1_x86_64.whl (11.6 MB)
Requirement already satisfied: future in /home/shmpwk/venv/lib/python3.6/site-packages (from scikit-robot) (0.18.2)
Collecting gdown
  Using cached gdown-3.12.2.tar.gz (8.2 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/shmpwk/venv/bin/python3 /home/shmpwk/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpp777k68r
       cwd: /tmp/pip-install-kkua2b1c/gdown
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/shmpwk/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/shmpwk/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/shmpwk/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/shmpwk/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/shmpwk/venv/bin/python3 /home/shmpwk/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpp777k68r Check the logs for full command output.
WARNING: You are using pip version 20.2; however, version 20.2.4 is available.
You should consider upgrading via the '/home/shmpwk/venv/bin/python3 -m pip install --upgrade pip' command.
```

My environment is :
- venv, python3.6
- pip 20.2

**Comment by shmpwk** [comment]
I downgrade pip like
```
$ pip install pip==18.1
```
and succeeded to pip install scikit-robot.
